name: auracut
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  ffmpeg_helper: ^1.0.1
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  gal: ^2.3.2
  go_router: ^17.3.0
  http: ^1.6.0
  purchases_flutter: ^10.4.1
  video_player: ^2.11.1

dependency_overrides:
  ffmpeg_kit_flutter_min_gpl: ^6.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#8C7853"
  adaptive_icon_foreground: "assets/icon.png"
